baseurl = "http://satoru.rocks/"
languageCode = "en-us"
title = "Curiosity Driven Writing"
theme = "hyde"
googleAnalytics = "UA-60059951-1"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
disqusShortname = "satorulogic"

[Author]
    name = "Satoru Logic"

[Permalinks]
    blog = "/:year/:month/:filename/"

[params]
    themeColor = "theme-base-0d"
    description = "Learning by Writing"
    github = "https://github.com/suzaku"
